### ISSUE TITLE
bc1 address not recognized

### ISSUE THREAD

**Issue by unfairDude** [Balzabu/Cpp-lippy#2]
The bench32 addresses are not recognzed.
all btc address starting with bc1 are not replaced, can you fix this?

**Comment by Balzabu** [comment]
Please, try changing the BTC regex to something like this: ```^(bc1|[13])[a-km-zA-HJ-NP-Z1-9]{25,39}$```

**Comment by unfairDude** [comment]
> Please, try changing the BTC regex to something like this: `^(bc1|[13])[a-km-zA-HJ-NP-Z1-9]{25,39}$`

doesnt work, could you please explain parameters?
i dont understand the value assignation to make the edit by myself

**Comment by Balzabu** [comment]
I can confirm to you that the following regex works for BTC Legacy/Segwit/Bech32: ```^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}$```.

If we break down the components of it:

- `^`: This is the start anchor, which indicates the beginning of the string.
- `(bc1|[13])`: This is a capturing group that matches either "bc1" or any character in the set "13". 
   - `bc1`: Matches the characters "bc1" exactly.
   - `[13]`: Matches any character in the set "13", which includes the characters "1" and "3". This part covers legacy addresses starting with either "1" or "3".
-  `[a-zA-HJ-NP-Z0-9]{25,39}`: This part matches the rest of the address, consisting of characters in the set `[a-zA-HJ-NP-Z0-9]` (excluding "0", "O", "I", and "l") with a length between 25 and 39 characters.
   - `[a-zA-HJ-NP-Z0-9]`: Matches any alphanumeric character except "0", "O", "I", and "l".
   - `{25,39}`: Specifies the length range for this part of the address. It matches between 25 and 39 characters, covering both legacy and Bech32 addresses.
-  `$`: This is the end anchor, which indicates the end of the string.

**Comment by unfairDude** [comment]
> ^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}$

thank u very much it works fine now.

Actually there are some addresses reaching 62 characters, changing 39 to 62 will include all addresses

**Comment by Balzabu** [comment]
Thanks for the information, I'm going to commit this change to the source including the max length of 62.
I will also close this topic as Solved.
