### ISSUE TITLE
I'd like to add this coins to the clipper

### ISSUE THREAD

**Issue by DEV-Devound** [Balzabu/Cpp-lippy#3]
Could you help me? this are the coins.
Litecoin, Bitcoin Cash, Binance Coin, Polygon, Tron, Monero, Solana, USDT all chains, USDC all chains and DAI all chains

**Comment by annemarieshev** [comment]
What do you need help with?

**Comment by annemarieshev** [comment]
Do you have any issues with them ?

**Comment by Balzabu** [comment]
> Could you help me? this are the coins.
> Litecoin, Bitcoin Cash, Binance Coin, Polygon, Tron, Monero, Solana, USDT all chains, USDC all chains and DAI all chains

No, issue is closed :)
